on: 
  pull_request:
    branches:
      - main

name: Click here to see job results 

jobs:          
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
          
      - uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build    
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/cargo@v1
        id: clippy
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings
      - uses: actions-rs/cargo@v1
        id: fmt
        with:
          command: fmt
          args: --all -- --check
      
      - name: Slack Notification on Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2.2.0
      - name: Set Slack Footer
        run: |
            echo "SLACK_FOOTER=<$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID|Click here to go to the job logs>" >> $GITHUB_ENV
      - name: Set Slack Message
        if: job.steps.fmt.status == failure()
        run: echo "SLACK_MESSAGE=fmt failed" >> $GITHUB_ENV
      - name: Set Slack Message 2
        if: job.steps.clippy.status == failure()
        run: echo "SLACK_MESSAGE=clippy failed" >> $GITHUB_ENV
              
        env:
          SLACK_CHANNEL: Daniel hirshson
          SLACK_WEBHOOK: ${{ secrets.ACTION_MONITORING_SLACK }}
          SLACK_COLOR: '#FF0000'
          SLACK_ICON: ':robot:'
          SLACK_TITLE: 'Job failed :x:'
          SLACK_LINK_NAMES: true

          
      - name: Slack Notification on Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: Daniel hirshson
          SLACK_WEBHOOK: ${{ secrets.ACTION_MONITORING_SLACK }}
          SLACK_COLOR: '#008000'
          SLACK_ICON: ':robot:'
          SLACK_TITLE: 'Job finished successfully :v:'
          SLACK_LINK_NAMES: true
