on: 
  pull_request:
    branches:
      - main

name: Click here to see job results 

jobs:          
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
          
      - uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build    
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
          
      - uses: actions-rs/cargo@v1
        with:
          command: clippy::all
          args: --all-targets --all-features -- -D warnings
          
      - uses: ravsamhq/notify-slack-action@v1
        if: always()
        with:
           status: ${{job.status}}
           notification_title: '{workflow} has {status_message}'
           message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
           mention_users: 'D02UXB46116'
           mention_users_when: 'failure,warnings'
        env:
         SLACK_WEBHOOK_URL: ${{secrets.ACTION_MONITORING_SLACK}}
