name: Rust

on:
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Format
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
#         run: cargo fmt 
  
  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Clippy
      - uses: actions/checkout@v3
      - env:
          RUSTFLAGS: "-D warnings"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose
#       - run: cargo clippy --verbose
  
  cargo-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
      - uses: actions/checkout@v3
      - env:
          RUSTFLAGS: "-A warnings"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
#       - run: cargo build
  
      
